# Generated by Django 4.2.3 on 2023-08-03 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
