# Generated by Django 4.2.3 on 2023-08-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_rename_create_at_spotifytoken_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='token_type',
            field=models.TextField(),
        ),
    ]
